### ISSUE TITLE
Please define what a SLAM dataset is and why they are useful.

### ISSUE THREAD

**Issue by medined** [youngguncho/awesome-slam-datasets#14]
I found your page and was curious but there are no hints.

**Comment by CaptainTrunky** [comment]
SLAM Datasets are used for validating any algorithms that input some visual data (color images, depth scans, etc) and, potentially, some motion data like IMU readings. Goals and outputs are:
1) trajectory of a camera/an agent motion - mandatory (odometry task) 
2)a map of visited surroundings in one of possible forms - occupancy grid, 3d model, point cloud... (map reconstruction task) 
3) for a given "frame" - estimation of current position on a map (Localization task)

One possible example - a set of videos taken from a flying drone accompanied with GPS and IMU measurement.

**Comment by medined** [comment]
Thank you.
