### ISSUE TITLE
Typo in sheets

### ISSUE THREAD

**Issue by YuYuCong** [youngguncho/awesome-slam-datasets#19]
Nice job. :-)

And, there may be typos in the google [spreadsheets](https://sites.google.com/view/awesome-slam-datasets/manual) at D23.

![Screenshot from 2021-09-15 18-55-58](https://user-images.githubusercontent.com/30014869/133421412-507896ec-f908-47b3-9231-87471dde905f.png)

**Comment by youngguncho** [comment]
I appreciate your comment! I fixed it.
