### ISSUE TITLE
Applycation for Reprinting Article to PaopaoRobot 

### ISSUE THREAD

**Issue by Yvon-Shong** [youngguncho/awesome-slam-datasets#4]
您好，我是泡泡机器人SLAM的成员，泡泡机器人是中国最大的SLAM相关公益性学术组织，我们想申请转载您该repo下的文章到我们的微信公众号（泡泡机器人SLAM）推文，会注明来源和原文链接，希望您能同意。更多问题欢迎联系我，邮箱 daiwei.song@outlook.com

**Comment by youngguncho** [comment]
I used google translator to understand what you mentioned.  It's also 'OK' for sharing our repo. Just let me know your website or info. Thank you.
