### ISSUE TITLE
new UAV dataset

### ISSUE THREAD

**Issue by Yvon-Shong** [youngguncho/awesome-slam-datasets#5]
Hi, I find a new dataset from ICRA 2019. But I don't know how to add to the google form.
So I open an issue.
The UZH-FPV Drone Racing Dataset
High-speed, Aggressive 6DoF Trajectories for State Estimation and Drone Racing
http://rpg.ifi.uzh.ch/uzh-fpv.html
UAV
with GT pose
mono+imu+event cam
paper name: Are We Ready for Autonomous Drone Racing? The UZH-FPV Drone Racing Dataset

**Comment by youngguncho** [comment]
Thank you for your contribution! I added UZH drone racing dataset in the list. 
I will close the issue. Thank you.
