### ISSUE TITLE
KAIST' dataset

### ISSUE THREAD

**Issue by zjlooojoe** [youngguncho/awesome-slam-datasets#6]
hi,Thanks for your list! I have a question about the Encoder's data in KAIST dataset, how to use the Encoder's data?Because I dont know how to get the V/angle from the data's format. Do you have some advises or cases to handle it? 

5. Encoder
The 'sensor_data/encoder.csv ' file stores the incremental pulse count values of wheel encoder.
[timestamp, left count, right count]

**Comment by youngguncho** [comment]
Sorry for the late response. You can contact the first author of KAIST dataset paper for detailed information. As a simple response, you can use Ackerman's steering formula to compute the travel distance from Encoder counter values.

**Comment by youngguncho** [comment]
close issue.
