### ISSUE TITLE
FMDataset

### ISSUE THREAD

**Issue by zhuzunjie17** [youngguncho/awesome-slam-datasets#7]
Hi, thank you for the helpful list of SLAM dataset.

We have released a dataset called FMDataset, which aims to verify the robustness of Dense-SLAM system at different velocities of sensor motion. It can be found here:
https://github.com/zhuzunjie17/FastFusion

**Comment by youngguncho** [comment]
Sorry for the late response. I will add the dataset asap.

**Comment by youngguncho** [comment]
We add FMDataset in the list. Sorry for the late update.
