### ISSUE TITLE
What's 'year' item about?

### ISSUE THREAD

**Issue by GideonWeng** [youngguncho/awesome-slam-datasets#9]
Does the 'year' refer to the record time or the paper published time?

**Comment by youngguncho** [comment]
Originally, 'Year' means the 'open' or 'release' year of the dataset. But if the dataset has a new update, such as publication or sensor data addition,  'year' of the dataset can be changed.

**Comment by GideonWeng** [comment]
Gotcha, thx!

**Comment by GideonWeng** [comment]
The google site seems not update yet. Does it mean you have to edit it manually?

**Comment by youngguncho** [comment]
Yes, I need to update manually. I'm currently deciding to merge two sites (github & google site). Which site do you prefer to use? or easy to check the datasets?

**Comment by GideonWeng** [comment]
I'd say I like google site better, for it is cleaner. Considering Google site may be **banned** by some countries, github page can be easier for spreading the repo.

**Comment by youngguncho** [comment]
Thank you for the comment. I will continue updating both repositories.
